# Generated by Django 4.2.10 on 2024-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='0114680821', max_length=10),
        ),
    ]
