# Generated by Django 4.2.10 on 2024-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_alter_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='0114680821', max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=10),
        ),
    ]
